apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'parseconfig'
description: 'Parse Config File'

# These are only the properties that the DevOps team allows the devs to
# override in their yaml file. ${{ vars.* }} cannot be read inside a custom
# action, so they must be passed in as an input to the custom action. This
# also means all the vars must be defined on the platform.
inputs:
  CONFIG_FILE:
    description: 'asdf'
  I-CONTEXT:
    description: 'asdf'
  I-MVN-COMPILE-ARGS:
    description: 'asdf'
  I-MVN-TEST-ARGS:
    description: 'asdf'
  I-PY-TEST-ARGS:
    description: 'asdf'
  I-DOCKERFILE:
    description: 'asdf'

outputs:
  NAME:
    description: 'asdf'
    value: ${{ steps.parseconfigcba.outputs.name }}
  TECH:
    description: 'asdf'
    value: ${{ steps.parseconfigcba.outputs.tech }}
  CONTEXT:
    description: 'asdf'
    value: ${{ steps.parseconfigcba.outputs.context }}
  MVN-COMPILE-ARGS:
    description: 'asdf'
    value: ${{ steps.parseconfigcba.outputs.mvn-compile-args }}
  MVN-TEST-ARGS:
    description: 'asdf'
    value: ${{ steps.parseconfigcba.outputs.mvn-test-args }}
  PY-TEST-ARGS:
    description: 'asdf'
    value: ${{ steps.parseconfigcba.outputs.py-test-args }}
  PY-REQUIREMENTS:
    description: 'asdf'
    value: ${{ steps.parseconfigcba.outputs.py-requirements }}
  DOCKERFILE:
    description: 'asdf'
    value: ${{ steps.parseconfigcba.outputs.dockerfile }}
  SQ-PROJECT-KEY:
    description: 'asdf'
    value: ${{ steps.parseconfigcba.outputs.sq-project-key }}
  ARTIFACT-DESTINATION:
    description: 'asdf'
    value: ${{ steps.parseconfigcba.outputs.artifact-destination }}
  KANIKO-BUILD-ARGS:
    description: 'asdf'
    value: ${{ steps.parseconfigcba.outputs.kaniko-build-args }}
  KANIKO-LABELS:
    description: 'asdf'
    value: ${{ steps.parseconfigcba.outputs.kaniko-labels }}

runs:
  using: composite
  steps:
    - name: Parse Config
      id: parseconfigcba
      kind: build
      uses: docker://sbatchelder/platform-agent:parse-configv4
      shell: sh
      run: |
        python3 /tools/parse_config.py -f ${{ inputs.CONFIG_FILE }}
