apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
# kind: reusable_workflow
name: Image Builder
'on':
  push:
    branches:
      - '**'
jobs:
  ci:
    steps:
      - id: code-checkout
        name: Check out repo
        kind: build
        uses: cloudbees-io/checkout@v1
        with:
          provider: ${{ cloudbees.scm.provider }}
          repository: ${{ cloudbees.scm.repository }}

      - name: Log in to OCI registry
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: docker.io
          username: sbatchelder@cloudbees.com
          password: ${{ secrets.SBATCHELDER_DOCKERHUB_TOKEN }}

      - id: kaniko
        name: Upload via Kaniko
        uses: cloudbees-io/kaniko@v1
        with:
            dockerfile: "Dockerfile"
            context: "."
            destination: "sbatchelder/platform-agent:parse-configv5"
            labels: "maintainer=sbatchelder"
